#!/usr/bin/env node
// Generates migrations/0005b_voicebank_seed.sql from canon/seed/voicebank.json (SPEC_V3
// section AA), the way build_seed.mjs generates 0002_seed.sql. The rules live once, in
// src/voicebank.ts (validateSeedFile, lineId, SEED_STAMP): this script loads that module
// and refuses a file that breaks them. Deterministic ids and a fixed stamp, so a rebuild
// changes nothing already applied; every row is INSERT OR IGNORE, status unapproved,
// origin seed. She reads none of these until the owner approves them in the app.
//
// The module is TypeScript with extensionless imports, so: (1) when this Node cannot strip
// types it re-runs itself with --experimental-strip-types, and (2) a resolve hook maps
// "./db" to "./db.ts" (the same hook tests/unit/helpers.mjs registers).
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { registerHooks } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";

const SEED = "canon/seed/voicebank.json";
const OUT = "migrations/0005b_voicebank_seed.sql";

if (!process.features.typescript) {
  const r = spawnSync(process.execPath, ["--experimental-strip-types", ...process.argv.slice(1)], { stdio: "inherit" });
  process.exit(r.status ?? 1);
}

const HAS_EXTENSION = /\.(?:[cm]?[jt]s|json|node|wasm)$/i;
function isDirectory(p) {
  try { return statSync(p).isDirectory(); } catch { return false; }
}
registerHooks({
  resolve(specifier, context, nextResolve) {
    const relative = specifier.startsWith("./") || specifier.startsWith("../");
    const parent = context.parentURL;
    if (relative && !HAS_EXTENSION.test(specifier) && typeof parent === "string" && parent.startsWith("file:")) {
      const base = fileURLToPath(new URL(specifier, parent));
      if (existsSync(base + ".ts")) return nextResolve(pathToFileURL(base + ".ts").href, context);
      if (isDirectory(base) && existsSync(base + "/index.ts")) return nextResolve(pathToFileURL(base + "/index.ts").href, context);
    }
    return nextResolve(specifier, context);
  },
});

const { SEED_STAMP, SEED_TOTAL, lineId, normalizeLineText, validateSeedFile } = await import(new URL("../src/voicebank.ts", import.meta.url));

let entries;
try {
  entries = JSON.parse(readFileSync(SEED, "utf8"));
} catch (e) {
  console.error(`voicebank: cannot read ${SEED}: ${e instanceof Error ? e.message : String(e)}`);
  process.exit(1);
}

const problems = validateSeedFile(entries);
if (problems.length) {
  console.error(`voicebank: ${SEED} breaks the drafting rules (${problems.length}):`);
  for (const p of problems) console.error("  " + p);
  process.exit(1);
}

const q = (v) => (v === null || v === undefined) ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const out = [];
out.push(`-- Generated by scripts/build_voicebank.mjs from ${SEED}. Do not edit by hand; edit the JSON and rebuild.`);
out.push(`-- v3 (SPEC_V3 section AA): the voice bank seed, ${SEED_TOTAL} lines, every one unapproved until the owner decides.`);
out.push("-- Deterministic ids and a fixed stamp; INSERT OR IGNORE, so a re-run changes nothing already applied.");
const ids = new Set();
for (const e of entries) {
  const text = e.text.trim();
  const id = await lineId(text);
  if (ids.has(id)) {
    console.error(`voicebank: id collision on ${JSON.stringify(text)}`);
    process.exit(1);
  }
  ids.add(id);
  out.push(
    `INSERT OR IGNORE INTO voice_lines (id, text, text_norm, tags_json, source, origin, status, uses, last_used_at, created_at, updated_at, decided_at) VALUES (${q(id)}, ${q(text)}, ${q(normalizeLineText(text))}, ${q(JSON.stringify(e.tags))}, ${q(e.source ?? null)}, 'seed', 'unapproved', 0, NULL, ${q(SEED_STAMP)}, ${q(SEED_STAMP)}, NULL);`,
  );
}
writeFileSync(OUT, out.join("\n") + "\n");
console.log(`voicebank: ${entries.length} lines validated -> ${OUT}`);
