#!/usr/bin/env node
// Generates migrations/0002_seed.sql from canon/seed/*.json. Deterministic ids so the
// migration is stable across rebuilds. Fresh start: no shared history, no facts about
// him, no protected unknowns. Her private truths are seeded undisclosed.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";

const facts = JSON.parse(readFileSync("canon/seed/facts.json", "utf8"));
const state = JSON.parse(readFileSync("canon/seed/state.json", "utf8"));
const assets = JSON.parse(readFileSync("canon/seed/assets.json", "utf8"));
const settings = JSON.parse(readFileSync("canon/seed/settings.json", "utf8"));

const T = "2026-09-24T00:00:00.000Z";
const q = (v) => (v === null || v === undefined) ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const idOf = (...parts) => "seed-" + createHash("sha256").update(parts.join("|")).digest("hex").slice(0, 16);

const out = [];
out.push("-- Generated by scripts/build_seed.mjs. Do not edit by hand; edit canon/seed/*.json and rebuild.");

facts.forEach((f, i) => {
  const id = idOf("fact", f.scope, f.subject, f.fact);
  out.push(`INSERT INTO facts (id, scope, subject, fact, source, status, disclosed, provisional, version, supersedes_id, created_at, updated_at) VALUES (${q(id)}, ${q(f.scope)}, ${q(f.subject)}, ${q(f.fact)}, ${q(f.source)}, 'approved', ${f.disclosed ? 1 : 0}, ${f.provisional ? 1 : 0}, 1, NULL, ${q(T)}, ${q(T)});`);
});

out.push(`INSERT INTO state_versions (id, entity, version, state_json, source, note, created_at) VALUES (${q(idOf("state", "relationship", 1))}, 'relationship', 1, ${q(JSON.stringify(state.relationship))}, 'seed', 'Fresh start, 2026-09-24. She has not met him.', ${q(T)});`);
out.push(`INSERT INTO state_versions (id, entity, version, state_json, source, note, created_at) VALUES (${q(idOf("state", "scene", 1))}, 'scene', 1, ${q(JSON.stringify(state.scene))}, 'seed', 'No scene in progress.', ${q(T)});`);

for (const a of assets) {
  out.push(`INSERT INTO visual_assets (id, file, role, sha256, bytes, approval_status, notes, created_at) VALUES (${q(a.id)}, ${q(a.file)}, ${q(a.role)}, ${q(a.sha256)}, ${a.bytes === null || a.bytes === undefined ? "NULL" : a.bytes}, ${q(a.approval_status)}, ${q(a.notes)}, ${q(T)});`);
}

// 0002 is applied on the live database and is never edited: a settings key a later
// migration inserts (INSERT OR IGNORE INTO settings, 0008_v4.sql onward) is that migration's
// row, not a new line here. canon/seed/settings.json still carries every default.
const laterKeys = new Set();
for (const f of readdirSync("migrations").filter((n) => n.endsWith(".sql") && n !== "0002_seed.sql")) {
  for (const m of readFileSync("migrations/" + f, "utf8").matchAll(/INSERT OR IGNORE INTO settings \(key, value, updated_at\) VALUES \('([A-Za-z0-9]+)'/g)) laterKeys.add(m[1]);
}
let seeded = 0;
for (const [k, v] of Object.entries(settings)) {
  if (laterKeys.has(k)) continue;
  seeded++;
  out.push(`INSERT INTO settings (key, value, updated_at) VALUES (${q(k)}, ${q(JSON.stringify(v))}, ${q(T)});`);
}

out.push(`INSERT INTO audit_events (id, actor, action, entity, entity_id, before_json, after_json, created_at) VALUES (${q(idOf("audit", "seed"))}, 'system', 'seed', 'database', NULL, NULL, ${q(JSON.stringify({ facts: facts.length, assets: assets.length, note: "Fresh start at 22. Music anchor list removed per Justin 2026-09-24." }))}, ${q(T)});`);

writeFileSync("migrations/0002_seed.sql", out.join("\n") + "\n");
console.log(`seed: ${facts.length} facts, 2 state versions, ${assets.length} assets, ${seeded} settings (${laterKeys.size} left to later migrations) -> migrations/0002_seed.sql`);
