#!/usr/bin/env node
// Vendors ElevenLabs' official browser client (SPEC_V4 Amendment A2, lane L10).
//
// The package @elevenlabs/client ships an IIFE bundle (dist/lib.iife.js, the "unpkg"
// export, livekit-client bundled in) and two AudioWorklet files. This script copies them
// into public/js/vendor/ as same-origin files, so the page never loads a script from a
// CDN and the CSP stays default-src 'self':
//   public/js/vendor/elevenlabs-client.js            the IIFE wrapped as an ES module
//   public/js/vendor/worklets/rawAudioProcessor.js    the WebSocket transport's worklets,
//   public/js/vendor/worklets/audioConcatProcessor.js self-hosted (no blob: in script-src)
//
// The wrap: the bundle declares `var ElevenLabsClient = (function (exports) {...})({})`
// at the top level, which is module-scoped inside an ES module, so the file ends with
// `export const { Conversation, ... } = ElevenLabsClient` for every name the bundle
// exports, plus a default export. The source-map comment is dropped (the map is not
// vendored). Every em dash, en dash and Unicode ellipsis in the bundle's comments and
// strings becomes " -- ", "-" or "..." (the repo's typography rule; none of the 24 sit in
// a regular expression or an identifier, checked on 1.25.0).
//
//   node scripts/vendor_elevenlabs.mjs           write the files
//   node scripts/vendor_elevenlabs.mjs --check   exit 1 when the files on disk differ
//
// Generated files are never edited by hand: change this script and rerun it.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const PACKAGE_DIR = join(ROOT, "node_modules", "@elevenlabs", "client");
export const VENDOR_DIR = join(ROOT, "public", "js", "vendor");
export const CLIENT_FILE = "elevenlabs-client.js";
export const WORKLET_DIR = "worklets";
export const WORKLET_FILES = Object.freeze(["rawAudioProcessor.js", "audioConcatProcessor.js"]);
export const HEADER_PREFIX = "// @elevenlabs/client ";

const EM_DASH = String.fromCharCode(0x2014);
const EN_DASH = String.fromCharCode(0x2013);
const ELLIPSIS = String.fromCharCode(0x2026);
const BAD = new RegExp("[" + EM_DASH + EN_DASH + ELLIPSIS + "]");

// The repo's typography rule applied to vendored text: " -- ", "-" and "...".
export function asciiTypography(text) {
  return text
    .split(" " + EM_DASH + " ").join(" -- ")
    .split(EM_DASH).join("--")
    .split(EN_DASH).join("-")
    .split(ELLIPSIS).join("...");
}

// The names the IIFE assigns on its exports object, in source order, unique.
export function exportedNames(iife) {
  const names = [];
  for (const m of iife.matchAll(/\bexports\.([A-Za-z_$][A-Za-z0-9_$]*)\s*=/g)) {
    const name = m[1];
    if (!names.includes(name)) names.push(name);
  }
  return names;
}

function header(version, what) {
  return HEADER_PREFIX + version + " (MIT, ElevenLabs), " + what + ". Generated by scripts/vendor_elevenlabs.mjs; do not edit.\n";
}

// The ES-module wrap of the IIFE bundle.
export function wrapIife(iife, version) {
  const body = iife.replace(/\n\/\/# sourceMappingURL=[^\n]*\n?$/, "\n");
  if (!/^\s*var ElevenLabsClient = \(function/.test(body)) throw new Error("lib.iife.js does not start with `var ElevenLabsClient = (function`");
  const names = exportedNames(body);
  if (!names.includes("Conversation")) throw new Error("lib.iife.js exports no Conversation");
  return (
    header(version, "the browser client as one same-origin ES module") +
    asciiTypography(body) +
    "\nexport const { " + names.join(", ") + " } = ElevenLabsClient;\n" +
    "export default ElevenLabsClient;\n"
  );
}

// Every file to write, keyed by its path under public/js/vendor/.
export function buildVendorFiles(packageDir = PACKAGE_DIR) {
  const pkg = JSON.parse(readFileSync(join(packageDir, "package.json"), "utf8"));
  const version = String(pkg.version);
  const iife = readFileSync(join(packageDir, "dist", "lib.iife.js"), "utf8");
  const out = { [CLIENT_FILE]: wrapIife(iife, version) };
  for (const name of WORKLET_FILES) {
    const text = readFileSync(join(packageDir, "worklets", name), "utf8");
    out[WORKLET_DIR + "/" + name] = header(version, "AudioWorklet " + name.replace(/\.js$/, "") + " for the WebSocket transport") + asciiTypography(text);
  }
  for (const [path, text] of Object.entries(out)) {
    if (BAD.test(text)) throw new Error("typography: " + path + " still carries a dash or an ellipsis character");
  }
  return { version, files: out };
}

function main() {
  const check = process.argv.includes("--check");
  if (!existsSync(PACKAGE_DIR)) {
    console.error("vendor_elevenlabs: @elevenlabs/client is not installed (npm install)");
    process.exit(1);
  }
  const { version, files } = buildVendorFiles();
  let differ = 0;
  for (const [rel, text] of Object.entries(files)) {
    const full = join(VENDOR_DIR, rel);
    if (check) {
      const current = existsSync(full) ? readFileSync(full, "utf8") : null;
      if (current !== text) {
        differ++;
        console.error("vendor_elevenlabs: " + rel + (current === null ? " is missing" : " differs from the installed package"));
      }
      continue;
    }
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, text);
    console.log("vendor_elevenlabs: wrote public/js/vendor/" + rel + " (" + text.length + " chars)");
  }
  if (check) {
    if (differ) process.exit(1);
    console.log("vendor_elevenlabs: public/js/vendor matches @elevenlabs/client " + version);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
