// Blind tastings (SPEC_V3 HH). Nothing new in the story: this is his instrument. The same
// turn is generated by two performers side by side, shown blind (Left and Right), he picks
// which one is her, a ledger keeps the wins per performer, and a winner can be promoted to
// the live performer with one click. Both drafts go through the same prompt, the same
// markers, the same checks and the same one retry (chat.ts's pieces: prepareTurn,
// generateDraft, commitReply); the loser is never stored as a message. A tasting turn
// spends double and is capped separately (budget.assertTastingBudget).
//
// While a tasting is pending its user message sits stored with no reply, which is exactly
// the shape runTurn treats as a died turn to resume; prepareTurn's pending-tasting gate
// (chat.ts pendingTastingGate) answers 409 tasting_pending to every other turn shape until
// he picks, hands the tasting back for replay to a tasting turn with the same key, and
// expires an abandoned one (30 minutes; nightly too, through expireStaleStmts).
import { GenerateFailure, afterReply, commitReply, draftFromStored, generateDraft, prepareTurn, recordRuns, runStatements } from "./chat";
import type { Generated, Performer as ChatPerformer, Prepared } from "./chat";
import { assertBudget, assertTastingBudget, hasPrice } from "./budget";
import { providerConfigured } from "./providers/index";
import { readContext, writeContext } from "./provenance";
import { seededUnit } from "./life";
import { auditStmt, getMessage, insertMessageStmt, newId, nextSeq, nowIso, putSettings, touchConversationStmt } from "./db";
import { ApiHttpError } from "./errors";
import { ProviderError } from "./types";
import type { Env, Flag, MessageRow, ProviderName, Settings, TurnResponse } from "./types";
import type { SongRef } from "./markers";

const MICRO = 1_000_000;
export const TASTING_EXPIRY_MS = 30 * 60 * 1000;
const RECENT_LIMIT = 20;

// ------------------------------------------------------------------ types

export type Side = "A" | "B";
export type Pick = "left" | "right" | "neither";
export type TastingStatus = "pending" | "picked" | "void" | "expired";

export interface TastingRow {
  id: string;
  conversation_id: string;
  user_message_id: string;
  idempotency_key: string;
  left_side: Side;
  status: TastingStatus;
  a_provider: string;
  a_model: string;
  b_provider: string;
  b_model: string;
  pick: Pick | null;
  winner_side: Side | null;
  cost_usd_micro: number;
  created_at: string;
  decided_at: string | null;
}

export interface TastingCandidateRow {
  id: string;
  tasting_id: string;
  side: Side;
  text: string;
  photo: string | null;
  song_json: string | null;
  clip: string | null;
  flags_json: string | null;
  run_id: string;
  retried: number;
  cost_usd_micro: number;
  created_at: string;
}

export interface Performer {
  provider: string;
  model: string;
}

export interface BlindCandidate {
  side: "left" | "right";
  text: string;
  flags: string[];
  photo: boolean;
  song: SongRef | null;
}

export interface TastingResponse {
  tastingId: string;
  conversationId: string;
  userMessage: MessageRow;
  candidates: BlindCandidate[];
  expiresAt: string;
  replayed: boolean;
}

export interface RevealedTasting {
  id: string;
  conversationId: string;
  userMessageId: string;
  status: TastingStatus;
  pick: Pick | null;
  winnerSide: Side | null;
  left: Performer;
  right: Performer;
  winner: Performer | null;
  loser: Performer | null;
  costUsd: number;
  createdAt: string;
  decidedAt: string | null;
}

export interface PickResponse {
  tasting: RevealedTasting;
  assistantMessage: MessageRow | null;
}

export interface LedgerRow {
  performer: string;
  provider: string;
  model: string;
  wins: number;
  losses: number;
  draws: number;
  rate: number;
  lastPickedAt: string | null;
}

export interface Ledger {
  performers: LedgerRow[];
  recent: RevealedTasting[];
}

// ------------------------------------------------------------------ pure pieces

// Which performer sits on the left, from the tasting id alone: deterministic and balanced.
export function leftSideFor(tastingId: string): Side {
  return seededUnit(tastingId) < 0.5 ? "A" : "B";
}

export function sideOf(row: { left_side: Side }, which: "left" | "right"): Side {
  if (which === "left") return row.left_side;
  return row.left_side === "A" ? "B" : "A";
}

export function performerOf(row: TastingRow, side: Side): Performer {
  return side === "A" ? { provider: row.a_provider, model: row.a_model } : { provider: row.b_provider, model: row.b_model };
}

export function performerKey(p: Performer): string {
  return p.provider + " " + p.model;
}

export function expiresAtOf(row: { created_at: string }): string {
  const t = Date.parse(row.created_at);
  return new Date((Number.isFinite(t) ? t : Date.now()) + TASTING_EXPIRY_MS).toISOString();
}

// Older than 30 minutes: the row, or its created_at alone.
export function isExpired(row: { created_at: string } | string, now: Date | number): boolean {
  const t = Date.parse(typeof row === "string" ? row : row.created_at);
  const at = typeof now === "number" ? now : now.getTime();
  return !Number.isFinite(t) || at - t > TASTING_EXPIRY_MS;
}

function parseFlags(json: string | null): Flag[] {
  if (!json) return [];
  try {
    const v: unknown = JSON.parse(json);
    return Array.isArray(v) ? v.filter((f): f is Flag => typeof f === "object" && f !== null && typeof (f as Flag).code === "string") : [];
  } catch {
    return [];
  }
}

function parseSong(json: string | null): SongRef | null {
  if (!json) return null;
  try {
    const v = JSON.parse(json) as SongRef;
    return v && typeof v === "object" && typeof v.artist === "string" && typeof v.title === "string" ? v : null;
  } catch {
    return null;
  }
}

// A stored performer for chat.ts, whose Performer names the provider narrowly.
function chatPerformer(p: Performer): ChatPerformer {
  return { provider: p.provider as ProviderName, model: p.model };
}

// The blind view: Left and Right in that order, no provider or model anywhere.
export function blindCandidates(row: { left_side: Side }, candidates: TastingCandidateRow[]): BlindCandidate[] {
  const bySide = new Map(candidates.map((c) => [c.side, c] as const));
  return (["left", "right"] as const).map((which) => {
    const c = bySide.get(sideOf(row, which));
    return {
      side: which,
      text: c ? c.text : "",
      flags: c ? parseFlags(c.flags_json).map((f) => f.code) : [],
      photo: !!(c && c.photo),
      song: c ? parseSong(c.song_json) : null,
    };
  });
}

export const blindResponse = blindCandidates;

export function reveal(row: TastingRow): RevealedTasting {
  const left = performerOf(row, sideOf(row, "left"));
  const right = performerOf(row, sideOf(row, "right"));
  const winner = row.winner_side ? performerOf(row, row.winner_side) : null;
  const loser = row.winner_side ? performerOf(row, row.winner_side === "A" ? "B" : "A") : null;
  return {
    id: row.id,
    conversationId: row.conversation_id,
    userMessageId: row.user_message_id,
    status: row.status,
    pick: row.pick,
    winnerSide: row.winner_side,
    left,
    right,
    winner,
    loser,
    costUsd: (row.cost_usd_micro ?? 0) / MICRO,
    createdAt: row.created_at,
    decidedAt: row.decided_at,
  };
}

// The ledger arithmetic over every picked or void tasting: wins, losses, draws (neither),
// rate = wins / (wins + losses), last picked at.
export function ledgerFrom(rows: TastingRow[]): LedgerRow[] {
  const table = new Map<string, LedgerRow>();
  const get = (p: Performer): LedgerRow => {
    const k = performerKey(p);
    let r = table.get(k);
    if (!r) {
      r = { performer: k, provider: p.provider, model: p.model, wins: 0, losses: 0, draws: 0, rate: 0, lastPickedAt: null };
      table.set(k, r);
    }
    return r;
  };
  for (const row of rows) {
    if (row.status !== "picked" && row.status !== "void") continue;
    const a = get(performerOf(row, "A"));
    const b = get(performerOf(row, "B"));
    if (row.status === "void" || !row.winner_side) {
      a.draws += 1;
      b.draws += 1;
      continue;
    }
    const w = row.winner_side === "A" ? a : b;
    const l = row.winner_side === "A" ? b : a;
    w.wins += 1;
    l.losses += 1;
    if (row.decided_at && (!w.lastPickedAt || row.decided_at > w.lastPickedAt)) w.lastPickedAt = row.decided_at;
  }
  const out = Array.from(table.values());
  for (const r of out) r.rate = r.wins + r.losses ? r.wins / (r.wins + r.losses) : 0;
  out.sort((x, y) => y.wins - x.wins || x.performer.localeCompare(y.performer));
  return out;
}

// ------------------------------------------------------------------ rows

export async function getTasting(db: D1Database, id: string): Promise<TastingRow | null> {
  if (typeof id !== "string" || !id || id.length > 120) return null;
  return db.prepare("SELECT * FROM tastings WHERE id = ?1").bind(id).first<TastingRow>();
}

export async function listCandidates(db: D1Database, tastingId: string): Promise<TastingCandidateRow[]> {
  const r = await db.prepare("SELECT * FROM tasting_candidates WHERE tasting_id = ?1 ORDER BY side ASC").bind(tastingId).all<TastingCandidateRow>();
  return r.results;
}

// Pending older than 30 minutes -> expired (the nightly maintenance, the gate, the pick).
export function expireStaleStmts(db: D1Database, now: Date): D1PreparedStatement[] {
  const cutoff = new Date(now.getTime() - TASTING_EXPIRY_MS).toISOString();
  return [db.prepare("UPDATE tastings SET status = 'expired', decided_at = ?2 WHERE status = 'pending' AND created_at < ?1").bind(cutoff, now.toISOString())];
}

function tastingStmt(db: D1Database, t: TastingRow): D1PreparedStatement {
  return db.prepare("INSERT INTO tastings (id, conversation_id, user_message_id, idempotency_key, left_side, status, a_provider, a_model, b_provider, b_model, pick, winner_side, cost_usd_micro, created_at, decided_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15)")
    .bind(t.id, t.conversation_id, t.user_message_id, t.idempotency_key, t.left_side, t.status, t.a_provider, t.a_model, t.b_provider, t.b_model, t.pick, t.winner_side, t.cost_usd_micro, t.created_at, t.decided_at);
}

function candidateStmt(db: D1Database, c: TastingCandidateRow): D1PreparedStatement {
  return db.prepare("INSERT INTO tasting_candidates (id, tasting_id, side, text, photo, song_json, clip, flags_json, run_id, retried, cost_usd_micro, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)")
    .bind(c.id, c.tasting_id, c.side, c.text, c.photo, c.song_json, c.clip, c.flags_json, c.run_id, c.retried, c.cost_usd_micro, c.created_at);
}

function tastingSettingsOf(settings: Settings): { enabled: boolean; provider: ProviderName; model: string } {
  return {
    enabled: settings.tastingEnabled === true,
    provider: (typeof settings.tastingProvider === "string" ? settings.tastingProvider : "openai") as ProviderName,
    model: typeof settings.tastingModel === "string" && settings.tastingModel.trim() ? settings.tastingModel.trim() : "gpt-4.1",
  };
}

function errorClass(e: unknown): string {
  if (e instanceof ProviderError) return e.kind;
  if (e instanceof Error) return e.name || "Error";
  return "error";
}

// ------------------------------------------------------------------ the tasting turn

type SideResult = { ok: true; generated: Generated } | { ok: false; failure: GenerateFailure };

// One side through the shared pipeline piece; a failure or refusal comes back with its run
// rows (both runs are always recorded) instead of thrown.
async function runSide(env: Env, db: D1Database, settings: Settings, prepared: Prepared, performer: ChatPerformer): Promise<SideResult> {
  try {
    return { ok: true, generated: await generateDraft(env, db, settings, prepared, performer, "tasting") };
  } catch (e) {
    if (e instanceof GenerateFailure) return { ok: false, failure: e };
    throw e;
  }
}

async function replayTasting(db: D1Database, id: string): Promise<TastingResponse> {
  const row = await getTasting(db, id);
  if (!row) throw new ApiHttpError(409, "tasting_pending", "the tasting is missing", false, id);
  const [user, candidates] = await Promise.all([getMessage(db, row.user_message_id), listCandidates(db, row.id)]);
  if (!user) throw new ApiHttpError(409, "tasting_pending", "the tasting's message is missing", false, row.id);
  return { tastingId: row.id, conversationId: row.conversation_id, userMessage: user, candidates: blindCandidates(row, candidates), expiresAt: expiresAtOf(row), replayed: true };
}

export async function runTastingTurn(
  env: Env,
  ctx: ExecutionContext,
  db: D1Database,
  settings: Settings,
  conversationId: string,
  content: string,
  idempotencyKey: string,
  actor: string,
): Promise<TastingResponse | TurnResponse> {
  const ts = tastingSettingsOf(settings);
  if (!ts.enabled) throw new ApiHttpError(400, "validation", "tastings are off; enable them on the Model page");
  // Side B's performer must be callable and priced before anything is spent.
  if (!providerConfigured(env, ts.provider)) throw new ApiHttpError(503, "provider_not_configured", `${ts.provider} is not configured`, false, ts.provider);
  if (!hasPrice(settings, ts.model)) throw new ApiHttpError(402, "price_unknown", `no price for model ${ts.model}; add it on the Model page before tasting`, false, ts.model);

  // Everything a turn needs, once; both sides share it (same prompt, same checks). The
  // gate inside hands a pending tasting with this key back as a replay and answers any
  // other pending one with 409 tasting_pending.
  const prepared = await prepareTurn(env, db, settings, conversationId, content, idempotencyKey, actor, { tasting: true });
  if (prepared.replay) return prepared.replay;
  if (prepared.tastingReplay) return replayTasting(db, prepared.tastingReplay.id);
  const estimate = prepared.estimateUsd;
  await assertTastingBudget(db, settings, estimate * 2);
  await assertBudget(db, settings, estimate * 2);

  // Both sides through the shared pipeline piece (same prompt, same checks, the same one
  // retry); a failed or refused side throws a GenerateFailure carrying its run rows.
  const performerA: ChatPerformer = prepared.performer;
  const performerB: ChatPerformer = { provider: ts.provider, model: ts.model };
  const [a, b] = await Promise.all([runSide(env, db, settings, prepared, performerA), runSide(env, db, settings, prepared, performerB)]);

  // One side failed or refused: void before it is stored, the survivor is an ordinary
  // reply flagged tasting_void, and both runs are still recorded.
  if (!a.ok || !b.ok) {
    if (!a.ok && !b.ok) {
      await recordRuns(db, [...a.failure.runs, ...b.failure.runs]);
      throw a.failure;
    }
    const survivor = (a.ok ? a : b) as { ok: true; generated: Generated };
    const failed = (a.ok ? b : a) as { ok: false; failure: GenerateFailure };
    const draft = survivor.generated.draft;
    draft.checks.flags.push({ code: "tasting_void", severity: "flag", detail: "the other performer failed or refused; this reply stands alone" });
    if (draft.flags && draft.flags !== draft.checks.flags) draft.flags.push(draft.checks.flags[draft.checks.flags.length - 1]!);
    await recordRuns(db, failed.failure.runs);
    const response = await commitReply(db, prepared, draft, survivor.generated.runs, {});
    afterReply(env, ctx, db, settings, response, draft.voice, actor);
    return response;
  }

  // Both drafts: the user message (when new), both sides' runs and usage, the tasting and
  // its two candidates, in one batch. No assistant message yet.
  const t = nowIso();
  const tastingId = newId("tst");
  const candidateOf = (g: Generated, side: Side): TastingCandidateRow => ({
    id: newId("tc"),
    tasting_id: tastingId,
    side,
    text: g.draft.text,
    photo: g.draft.photo,
    song_json: g.draft.song ? JSON.stringify(g.draft.song) : null,
    clip: null,
    flags_json: JSON.stringify(g.draft.checks.flags),
    run_id: g.draft.runId ?? g.runs[g.runs.length - 1]?.run.id ?? g.runs[0]?.run.id ?? "",
    retried: g.retried ? 1 : 0,
    cost_usd_micro: g.runs.reduce((n, r) => n + Math.max(0, r.micro), 0),
    created_at: t,
  });
  const candA = candidateOf(a.generated, "A");
  const candB = candidateOf(b.generated, "B");
  let userRow: MessageRow = prepared.existingUser ?? {
    id: newId("m"),
    conversation_id: conversationId,
    channel: "story",
    role: "user",
    content: prepared.text,
    created_at: t,
    seq: 0,
    idempotency_key: prepared.key,
    reply_to_id: null,
    model_run_id: null,
    flags_json: null,
    image_id: null,
    image_status: null,
    deliver_at: null,
    song_json: null,
    audio_key: null,
    images_json: null,
    media_id: null,
  };
  const row: TastingRow = {
    id: tastingId,
    conversation_id: conversationId,
    user_message_id: userRow.id,
    idempotency_key: prepared.key,
    left_side: leftSideFor(tastingId),
    status: "pending",
    a_provider: performerA.provider,
    a_model: performerA.model,
    b_provider: performerB.provider,
    b_model: performerB.model,
    pick: null,
    winner_side: null,
    cost_usd_micro: candA.cost_usd_micro + candB.cost_usd_micro,
    created_at: t,
    decided_at: null,
  };
  const build = async (): Promise<D1PreparedStatement[]> => {
    const stmts: D1PreparedStatement[] = [];
    if (!prepared.existingUser) {
      userRow = { ...userRow, seq: await nextSeq(db, conversationId), created_at: nowIso() };
      stmts.push(insertMessageStmt(db, userRow));
    }
    stmts.push(...runStatements(db, a.generated.runs), ...runStatements(db, b.generated.runs));
    stmts.push(tastingStmt(db, row), candidateStmt(db, candA), candidateStmt(db, candB));
    stmts.push(touchConversationStmt(db, conversationId, nowIso()));
    stmts.push(auditStmt(db, actor, "tasting.create", "tasting", tastingId, null, { conversationId, userMessageId: userRow.id, a: performerA, b: performerB, costUsd: row.cost_usd_micro / MICRO }));
    return stmts;
  };
  try {
    await db.batch(await build());
  } catch (e) {
    if (!(e instanceof Error && /UNIQUE constraint failed/i.test(e.message))) throw e;
    await db.batch(await build());
  }
  return { tastingId, conversationId, userMessage: userRow, candidates: blindCandidates(row, [candA, candB]), expiresAt: expiresAtOf(row), replayed: false };
}

// ------------------------------------------------------------------ the pick

export async function pickTasting(
  env: Env,
  ctx: ExecutionContext,
  db: D1Database,
  settings: Settings,
  id: string,
  pick: Pick,
  actor: string,
): Promise<PickResponse> {
  if (pick !== "left" && pick !== "right" && pick !== "neither") throw new ApiHttpError(400, "validation", "pick must be left, right or neither");
  const row = await getTasting(db, id);
  if (!row) throw new ApiHttpError(404, "not_found", "tasting not found");
  const now = new Date();
  if (row.status === "expired" || (row.status === "pending" && isExpired(row, now))) {
    if (row.status === "pending") await db.batch(expireStaleStmts(db, now));
    throw new ApiHttpError(409, "expired", "the tasting expired; retry the turn", false);
  }
  if (row.status !== "pending") throw new ApiHttpError(409, "already_decided", "the tasting is " + row.status, false);
  const t = nowIso();

  // Neither: void in the same batch as the audit, before the response returns; the user
  // message stays with no reply and the page's Retry (the same key) passes the gate.
  if (pick === "neither") {
    const r = await db.batch([
      db.prepare("UPDATE tastings SET status = 'void', pick = 'neither', decided_at = ?2 WHERE id = ?1 AND status = 'pending'").bind(id, t),
      auditStmt(db, actor, "tasting.pick", "tasting", id, { status: "pending" }, { status: "void", pick: "neither" }),
    ]);
    if (!r[0]?.meta.changes) throw new ApiHttpError(409, "already_decided", "the tasting was decided by another request", false);
    return { tasting: reveal({ ...row, status: "void", pick: "neither", decided_at: t }), assistantMessage: null };
  }

  const winnerSide = sideOf(row, pick);
  const candidates = await listCandidates(db, id);
  const winner = candidates.find((c) => c.side === winnerSide);
  if (!winner) throw new ApiHttpError(409, "already_decided", "the tasting has no candidate on that side", false);
  const user = await getMessage(db, row.user_message_id);
  if (!user) throw new ApiHttpError(409, "already_decided", "the tasting's message is missing", false);

  // Claim the pick (compare-and-set), so two taps never commit two replies; the turn is
  // then rebuilt through prepareTurn with the tasting's own key (the stored user row is
  // resumed; nothing is generated, so no budget or provider gate), and the winner is
  // committed through the shared commit piece. A failed commit hands the pick back.
  const claimed = await db.prepare("UPDATE tastings SET status = 'picked', pick = ?2, winner_side = ?3, decided_at = ?4 WHERE id = ?1 AND status = 'pending'").bind(id, pick, winnerSide, t).run();
  if (!claimed.meta.changes) throw new ApiHttpError(409, "already_decided", "the tasting was decided by another request", false);

  const winnerPerformer = performerOf(row, winnerSide);
  const loserPerformer = performerOf(row, winnerSide === "A" ? "B" : "A");
  let response: TurnResponse;
  try {
    const prepared = await prepareTurn(env, db, settings, row.conversation_id, user.content, row.idempotency_key, actor, { tasting: true, tastingPickId: id });
    if (prepared.replay) throw new ApiHttpError(409, "already_decided", "the message already has a reply", false);
    // The run rows were stored with the tasting, so the commit carries none; the
    // provenance names both performers.
    const draft = draftFromStored({
      text: winner.text,
      flags: parseFlags(winner.flags_json),
      photo: winner.photo,
      song: parseSong(winner.song_json),
      runId: winner.run_id,
      performer: chatPerformer(winnerPerformer),
    });
    response = await commitReply(db, prepared, draft, [], {
      runIdOverride: winner.run_id,
      tastingId: id,
      tasting: { id, winner: winnerPerformer, loser: loserPerformer },
      performer: chatPerformer(winnerPerformer),
    });
  } catch (e) {
    try {
      await db.prepare("UPDATE tastings SET status = 'pending', pick = NULL, winner_side = NULL, decided_at = NULL WHERE id = ?1 AND status = 'picked'").bind(id).run();
    } catch (e2) {
      console.error("tasting pick not handed back", errorClass(e2));
    }
    throw e;
  }

  // The provenance names both performers (never blind after a pick), then the audit and
  // the proposal pass over the stored exchange.
  try {
    const existing = (await readContext(db, response.assistantMessage.id)) ?? {};
    await writeContext(db, response.assistantMessage.id, { ...existing, tasting: { id, winner: winnerPerformer, loser: loserPerformer } });
  } catch (e) {
    console.warn("tasting provenance not written", errorClass(e));
  }
  await auditStmt(db, actor, "tasting.pick", "tasting", id, { status: "pending" }, { status: "picked", pick, winnerSide, winner: winnerPerformer, loser: loserPerformer, assistantMessageId: response.assistantMessage.id }).run();
  afterReply(env, ctx, db, settings, response, false, actor);
  return { tasting: reveal({ ...row, status: "picked", pick, winner_side: winnerSide, decided_at: t }), assistantMessage: response.assistantMessage };
}

// ------------------------------------------------------------------ ledger and promote

export async function ledger(db: D1Database): Promise<Ledger> {
  const r = await db.prepare("SELECT * FROM tastings WHERE status IN ('picked', 'void') ORDER BY decided_at DESC, created_at DESC LIMIT 2000").all<TastingRow>();
  const rows = r.results;
  return { performers: ledgerFrom(rows), recent: rows.slice(0, RECENT_LIMIT).map(reveal) };
}

// A winner becomes the live performer: the provider must be configured and the model
// priced (400 price_unknown; the panel asks for the two prices first).
export async function promote(db: D1Database, settings: Settings, env: Env, args: { provider: ProviderName; model: string }, actor: string): Promise<Settings> {
  const provider = args.provider;
  const model = typeof args.model === "string" ? args.model.trim() : "";
  if (!model || model.length > 200) throw new ApiHttpError(400, "validation", "model is required");
  if (!providerConfigured(env, provider)) throw new ApiHttpError(503, "provider_not_configured", `${provider} is not configured`, false, provider);
  if (!hasPrice(settings, model)) throw new ApiHttpError(400, "price_unknown", `no price for model ${model}; add its two prices on the Model page first`, false, model);
  const before = { provider: settings.provider, model: settings.model };
  const after = await putSettings(db, { provider, model });
  await auditStmt(db, actor, "tasting.promote", "settings", null, before, { provider: after.provider, model: after.model }).run();
  return after;
}
