// The v3 migrations: 0005_v3.sql carries every table and column SPEC_V3 names, the
// Portland fact, nothing destructive; 0005b is generated; the 0004 files still match HEAD.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { BAD_TYPOGRAPHY } from "./helpers.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const DIR = join(ROOT, "migrations");
const files = readdirSync(DIR).filter((f) => f.endsWith(".sql")).sort();
const read = (f) => readFileSync(join(DIR, f), "utf8");
const present = existsSync(join(DIR, "0005_v3.sql"));
const t = present ? test : (name, fn) => test.skip(name + " [skipped: migrations/0005_v3.sql not in this tree yet]", fn);

const TABLES = ["voice_lines", "voice_line_uses", "corrections", "memory_weights", "memory_recalls", "wants", "want_log", "asks", "grounding_log", "weather_cache", "calls", "tastings", "tasting_candidates", "message_marks"];
const COLUMNS = [["life_threads", "portrait_asset_id"], ["messages", "call_id"], ["message_context", "state_text"]];
const INDEXES = ["idx_voice_lines_status", "idx_voice_line_uses_conv", "idx_corrections_status", "idx_memory_recalls_conv", "idx_want_log_want", "idx_asks_status", "idx_grounding_log_occurred", "idx_calls_status", "idx_tastings_conv_status", "idx_tasting_candidates_tasting", "idx_messages_call"];

t("0005_v3.sql: every table, index and column of the consolidated migration", () => {
  const sql = read("0005_v3.sql");
  for (const table of TABLES) assert.ok(new RegExp("CREATE TABLE IF NOT EXISTS\\s+" + table + "\\b", "i").test(sql), table);
  for (const idx of INDEXES) assert.ok(new RegExp("CREATE INDEX IF NOT EXISTS\\s+" + idx + "\\b", "i").test(sql), idx);
  for (const [table, col] of COLUMNS) assert.ok(new RegExp("ALTER TABLE\\s+" + table + "\\s+ADD COLUMN\\s+" + col + "\\b", "i").test(sql), table + "." + col);
  assert.ok(/kind IN \('ai','clever','not_her','too_long','too_nice','too_polished','other'\)/.test(sql), "the correction kinds");
  assert.ok(/status IN \('starting','live','ended','failed','expired'\)/.test(sql), "the call statuses");
  assert.ok(/mark IN \('keep','drop'\)/.test(sql), "the marks");
  assert.ok(!BAD_TYPOGRAPHY.test(sql));
});

t("0005_v3.sql: her city as a fact (the owner's answer, 2026-09-24)", () => {
  const sql = read("0005_v3.sql");
  assert.ok(/INSERT[^;]*facts[^;]*Lives in Portland, Maine/i.test(sql), "the Portland fact insert");
  assert.ok(/'avelie'/.test(sql) && /'home'/.test(sql), "scope avelie, subject home");
  assert.ok(/Justin's decision 2026-09-24|Justin''s decision 2026-09-24/.test(sql), "the source");
});

t("v3 migrations never UPDATE, DELETE or DROP existing rows or tables", () => {
  const text = files.filter((f) => f.startsWith("0005")).map(read).join("\n");
  const body = text.split("\n").filter((l) => !l.trim().startsWith("--")).join("\n");
  assert.ok(!/^\s*(UPDATE|DELETE|DROP|TRUNCATE)\b/im.test(body), "found a destructive statement");
  assert.ok(!/ADD COLUMN[^;]*NOT NULL(?![^;]*DEFAULT)/i.test(body), "a NOT NULL column without a default cannot be added to a table with rows");
});

test("0005b_voicebank_seed.sql is generated (not hand-written) and only inserts", (tc) => {
  if (!existsSync(join(DIR, "0005b_voicebank_seed.sql"))) {
    tc.skip("migrations/0005b_voicebank_seed.sql not in this tree yet");
    return;
  }
  const sql = read("0005b_voicebank_seed.sql");
  assert.ok(/Generated by scripts\/build_voicebank\.mjs/i.test(sql), "the generated header");
  const body = sql.split("\n").filter((l) => l.trim() && !l.trim().startsWith("--"));
  assert.ok(body.every((l) => /^INSERT OR IGNORE INTO voice_lines/i.test(l)), "only INSERT OR IGNORE rows");
  assert.equal(body.length, 150);
});

test("the frozen migrations 0001 to 0004c match git HEAD", (tc) => {
  for (const f of ["0001_init.sql", "0003_messages_seq_unique.sql", "0004_life.sql", "0004b_push.sql", "0004c_voiceprint.sql", "0004d_media.sql"]) {
    if (!files.includes(f)) continue;
    let committed;
    try {
      committed = execFileSync("git", ["show", "HEAD:migrations/" + f], { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    } catch {
      tc.diagnostic("git not available or no HEAD; skipping the frozen check for " + f);
      continue;
    }
    assert.equal(read(f), committed, f + " differs from HEAD");
  }
});
