// The v2 migrations: numbered 0004 (0001 to 0003 are live and frozen), every table and
// column SPEC_V2 names present somewhere in them, nothing that touches existing rows.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const DIR = join(ROOT, "migrations");
const files = readdirSync(DIR).filter((f) => f.endsWith(".sql")).sort();
const read = (f) => readFileSync(join(DIR, f), "utf8");
const v2Text = files.filter((f) => f.startsWith("0004")).map(read).join("\n");

const hasTable = (name) => new RegExp("CREATE TABLE(?: IF NOT EXISTS)?\\s+" + name + "\\b", "i").test(v2Text);
const hasColumn = (table, col) => new RegExp("ALTER TABLE\\s+" + table + "\\s+ADD COLUMN\\s+" + col + "\\b", "i").test(v2Text);

test("v2 migrations are numbered 0004; no 0003_life exists; 0001 to 0003 are still there", () => {
  assert.ok(files.includes("0004_life.sql"), files.join(", "));
  assert.ok(!files.some((f) => /^0003_life/.test(f)), "0003 is taken by the live seq-unique migration");
  for (const f of ["0001_init.sql", "0002_seed.sql", "0003_messages_seq_unique.sql"]) assert.ok(files.includes(f), f);
});

test("0004_life.sql: the four tables of SPEC_V2 section F and the two message columns", () => {
  const t = read("0004_life.sql");
  for (const table of ["life_threads", "life_log", "message_context", "drift_reports"]) {
    assert.ok(new RegExp("CREATE TABLE(?: IF NOT EXISTS)?\\s+" + table + "\\b", "i").test(t), table);
  }
  assert.ok(/kind IN \('routine',\s*'event',\s*'person',\s*'place',\s*'arc'\)/.test(t), "the kind check");
  assert.ok(/ALTER TABLE messages ADD COLUMN deliver_at TEXT/.test(t));
  assert.ok(/ALTER TABLE messages ADD COLUMN song_json TEXT/.test(t));
});

test("the push, media, voice and voiceprint tables and columns exist in a 0004 migration", () => {
  assert.ok(hasTable("first_texts_daily"), "first_texts_daily (section R)");
  assert.ok(hasTable("push_subscriptions"), "push_subscriptions (section U)");
  assert.ok(hasTable("media_library"), "media_library (section V)");
  assert.ok(hasTable("voiceprints"), "voiceprints (section Y)");
  assert.ok(hasColumn("messages", "audio_key"), "messages.audio_key (section S)");
  assert.ok(hasColumn("messages", "images_json"), "messages.images_json (section T)");
  assert.ok(hasColumn("messages", "media_id"), "messages.media_id (section V)");
  assert.ok(existsSync(join(DIR, "0004b_push.sql")), "0004b_push.sql");
  assert.ok(existsSync(join(DIR, "0004c_voiceprint.sql")), "0004c_voiceprint.sql");
});

test("v2 migrations never UPDATE, DELETE or DROP existing rows or tables", () => {
  const lines = v2Text.split("\n").filter((l) => !l.trim().startsWith("--"));
  const body = lines.join("\n");
  assert.ok(!/^\s*(UPDATE|DELETE|DROP|TRUNCATE)\b/im.test(body), "found a destructive statement");
  assert.ok(!/ADD COLUMN[^;]*NOT NULL(?![^;]*DEFAULT)/i.test(body), "a NOT NULL column without a default cannot be added to a table with rows");
});

test("the frozen migrations 0001 to 0003 match git HEAD", (t) => {
  for (const f of ["0001_init.sql", "0002_seed.sql", "0003_messages_seq_unique.sql"]) {
    let committed;
    try {
      committed = execFileSync("git", ["show", "HEAD:migrations/" + f], { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    } catch {
      t.diagnostic("git not available or no HEAD; skipping the frozen check for " + f);
      continue;
    }
    if (f === "0002_seed.sql") {
      // The seed migration is regenerated by scripts/build_seed.mjs when the seed JSON
      // changes (the v2 settings rows); it may differ from HEAD, but only by INSERTs.
      const diff = read(f).split("\n").filter((l) => !committed.includes(l));
      for (const l of diff) assert.ok(/^\s*(INSERT|--|$)/.test(l) || /VALUES|\)\s*,?\s*;?\s*$/.test(l), "0002_seed.sql changed in a non-insert line: " + l.slice(0, 120));
      continue;
    }
    assert.equal(read(f), committed, f + " differs from HEAD");
  }
});
